env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/tmp/ci"
    USERNAME: ""
    EMAIL: ""
    SSHKEY1: ""
    SSHKEY2: ""

task:
  name: Ubuntu Touch - Xiaomi Redmi Note 10 Pro
  container:
    image: ubuntu:20.04
    cpu: 4
    memory: 8G

  setup_script:
    - apt update
    - apt install zip unzip android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
    - ln -sf python2.7 /usr/bin/python
    - wget https://raw.githubusercontent.com/LineageOS/android_system_core/lineage-17.1/mkbootimg/mkbootimg.py -O /usr/bin/mkbootimg
  directory_script:
    - git clone -b halium-11.0 --single-branch --depth="1" https://github.com/dopaemon/ubports-sweet.git /tmp/ci/UBPorts/xiaomi-sweet
  kernel_script:
    - export LC_ALL=C.UTF-8
    - cd /tmp/ci/UBPorts/xiaomi-sweet
    - git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-11 build
    - chmod +x build/build.sh
    - ./build/build.sh
    - ls out
