env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/tmp/ci"
    USERNAME: ""
    EMAIL: ""
    SSHKEY1: ""
    SSHKEY2: ""

task:
  name: Ubuntu Touch - Xiaomi Redmi Note 10 Pro
  container:
    image: ubuntu:20.04
    cpu: 4
    memory: 8G

  locate_script:
    - apt-get update && apt-get install -y locales
    - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
    - locale-gen en_US.UTF-8
  setup_script:
    - apt update
    - apt install zip unzip android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils git img2simg jq sudo wget xz-utils zip unzip -y --no-install-recommends
    - ln -sf python2.7 /usr/bin/python
    - wget https://raw.githubusercontent.com/LineageOS/android_system_core/lineage-17.1/mkbootimg/mkbootimg.py -O /usr/bin/mkbootimg
  directory_script:
    - git clone -b halium-11.0 --single-branch --depth="1" https://github.com/dopaemon/ubports-sweet.git /tmp/ci/UBPorts/xiaomi-sweet
  kernel_script:
    - cd /tmp/ci/UBPorts/xiaomi-sweet
    - git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-11 build
    - chmod +x build/build.sh
    - ./build/build.sh
    - ls out
    - mv out /tmp/ci/UBPorts/
  Xenial_script:
    - cd /tmp/ci/UBPorts/xiaomi-sweet
    - git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-11 build
    - export DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
    - chmod +x build/prepare-fake-ota.sh
    - ./build/prepare-fake-ota.sh out/device_$DEVICE.tar.xz ota
    - chmod +x build/system-image-from-ota.sh
    - ./build/system-image-from-ota.sh ota/ubuntu_command out
    - mv out/rootfs.img out/ubuntu.img
  flashable_script:
    - cd /tmp/ci/UBPorts/xiaomi-sweet
    - git clone -b sweet-11.0 https://github.com/KernelPanic-OpenSource/UBPorts.git
    - cp -r out/ubuntu.img UBPorts/data/
    - cp -r out/boot.img UBPorts/data/
    - cd UBPorts/
    - wget -O data/firmware-sweet.zip https://github.com/KernelPanic-OpenSource/UBPorts/releases/download/Miui-V12.5.9.0-Sweet/fw_sweet_miui_SWEETGlobal_V12.5.9.0.RKFMIXM_9a9a09a8de_11.0.zip
    - wget -O data/firmware-sweetin.zip https://github.com/KernelPanic-OpenSource/UBPorts/releases/download/Miui-V12.5.9.0-Sweet/fw_sweetin_miui_SWEETININGlobal_V12.5.10.0.RKFINXM_dd18557436_11.0.zip
    - zip -rv9 "UBPorts-Xenial-Sweet-halium-11.0-$(date +"%d-%m-%Y")-Devel.zip" *
    - mv UBPorts-Xenial* ../out
    - cd .. && ls out
