image: ubuntu:20.04

build:
  stage: build
  script:
    - apt update
    - apt install zip unzip android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
    - ln -sf python2.7 /usr/bin/python
    - wget https://raw.githubusercontent.com/LineageOS/android_system_core/lineage-17.1/mkbootimg/mkbootimg.py -O /usr/bin/mkbootimg
    - git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-11 build
    - ./build/build.sh
  artifacts:
    paths:
      - out/*

flashable-xenial:
  stage: deploy
  script:
    - apt update
    - apt install -y git img2simg jq sudo wget xz-utils zip unzip rclone
    - mkdir -p ~/.config/rclone
    - mkdir -p /root/.config/rclone
    - echo "$RCLONE" > ~/.config/rclone/rclone.conf
    - echo "$RCLONE" > /root/.config/rclone/rclone.conf
    - git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-11 build
    - DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
    - ./build/prepare-fake-ota.sh out/device_$DEVICE.tar.xz ota
    - mkdir -p out
    - ./build/system-image-from-ota.sh ota/ubuntu_command out
    - mv out/rootfs.img out/ubuntu.img
    - git clone -b sweet-11.0 https://github.com/KernelPanic-OpenSource/UBPorts.git
    - cp -r out/ubuntu.img UBPorts/data/
    - cp -r out/boot.img UBPorts/data/
    - cd UBPorts/
    - wget -O data/firmware-sweet.zip https://github.com/KernelPanic-OpenSource/UBPorts/releases/download/Miui-V12.5.9.0-Sweet/fw_sweet_miui_SWEETGlobal_V12.5.9.0.RKFMIXM_9a9a09a8de_11.0.zip
    - wget -O data/firmware-sweetin.zip https://github.com/KernelPanic-OpenSource/UBPorts/releases/download/Miui-V12.5.9.0-Sweet/fw_sweetin_miui_SWEETININGlobal_V12.5.10.0.RKFINXM_dd18557436_11.0.zip
    - zip -rv9 "UBPorts-Xenial-Sweet-halium-11.0-$(date +"%d-%m-%Y")-Devel.zip" *
    - rclone copy -v UBPorts-Xenial-Sweet-halium* cirrus:UBPorts/"$(date +'%d-%m-%Y')"/
    - cd ..
  artifacts:
    paths:
      - out/ubuntu.img
      - out/boot.img
  when: manual

flashable-focal:
  stage: deploy
  script:
    - apt update
    - apt install -y git img2simg jq sudo wget xz-utils zip unzip rclone
    - mkdir -p ~/.config/rclone
    - mkdir -p /root/.config/rclone
    - echo "$RCLONE" > ~/.config/rclone/rclone.conf
    - echo "$RCLONE" > /root/.config/rclone/rclone.conf
    - git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-11 build
    - DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
    - ROOTFS_URL="https://ci.ubports.com/job/focal-hybris-rootfs-arm64/job/master/lastSuccessfulBuild/artifact/ubuntu-touch-android9plus-rootfs-arm64.tar.gz" ./build/prepare-fake-ota.sh out/device_${DEVICE}_usrmerge.tar.xz ota
    - mkdir -p out
    - ./build/system-image-from-ota.sh ota/ubuntu_command out
    - mv out/rootfs.img out/ubuntu.img
    - git clone -b sweet-11.0 https://github.com/KernelPanic-OpenSource/UBPorts.git
    - cp -r out/ubuntu.img UBPorts/data/
    - cp -r out/boot.img UBPorts/data/
    - cd UBPorts/
    - wget -O data/firmware-sweet.zip https://github.com/KernelPanic-OpenSource/UBPorts/releases/download/Miui-V12.5.9.0-Sweet/fw_sweet_miui_SWEETGlobal_V12.5.9.0.RKFMIXM_9a9a09a8de_11.0.zip
    - wget -O data/firmware-sweetin.zip https://github.com/KernelPanic-OpenSource/UBPorts/releases/download/Miui-V12.5.9.0-Sweet/fw_sweetin_miui_SWEETININGlobal_V12.5.10.0.RKFINXM_dd18557436_11.0.zip
    - zip -rv9 "UBPorts-Focal-Sweet-halium-11.0-$(date +"%d-%m-%Y")-Devel.zip" *
    - rclone copy -v UBPorts-Focal-Sweet-halium* cirrus:UBPorts/"$(date +'%d-%m-%Y')"/
    - cd ..
  artifacts:
    paths:
      - out/boot.img
      - out/ubuntu.img
  when: manual

devel-flashable-xenial:
  stage: deploy
  script:
    - apt update
    - apt install -y git img2simg jq sudo wget xz-utils zip unzip rclone
    - mkdir -p ~/.config/rclone
    - mkdir -p /root/.config/rclone
    - echo "$RCLONE" > ~/.config/rclone/rclone.conf
    - echo "$RCLONE" > /root/.config/rclone/rclone.conf
    - git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-11 build
    - DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
    - ./build/prepare-fake-ota.sh out/device_$DEVICE.tar.xz ota
    - mkdir -p out
    - ./build/system-image-from-ota.sh ota/ubuntu_command out
    - mv out/rootfs.img out/ubuntu.img
    - git clone -b sweet-11.0 https://github.com/KernelPanic-OpenSource/UBPorts.git
    - cp -r out/ubuntu.img UBPorts/data/
    - cp -r out/boot.img UBPorts/data/
    - cd UBPorts/
    - wget -O data/firmware-sweet.zip https://github.com/KernelPanic-OpenSource/UBPorts/releases/download/Miui-V12.5.9.0-Sweet/fw_sweet_miui_SWEETGlobal_V12.5.9.0.RKFMIXM_9a9a09a8de_11.0.zip
    - wget -O data/firmware-sweetin.zip https://github.com/KernelPanic-OpenSource/UBPorts/releases/download/Miui-V12.5.9.0-Sweet/fw_sweetin_miui_SWEETININGlobal_V12.5.10.0.RKFINXM_dd18557436_11.0.zip
    - zip -rv9 "UBPorts-Xenial-Sweet-halium-11.0-$(date +"%d-%m-%Y")-Devel.zip" *
    - rclone copy -v UBPorts-Xenial-Sweet-halium* cirrus:Dev/UBPorts/"$(date +'%d-%m-%Y')"/
    - cd ..
  artifacts:
    paths:
      - out/ubuntu.img
      - out/boot.img

devel-flashable-focal:
  stage: deploy
  script:
    - apt update
    - apt install -y git img2simg jq sudo wget xz-utils zip unzip rclone
    - mkdir -p ~/.config/rclone
    - mkdir -p /root/.config/rclone
    - echo "$RCLONE" > ~/.config/rclone/rclone.conf
    - echo "$RCLONE" > /root/.config/rclone/rclone.conf
    - git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-11 build
    - DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
    - ROOTFS_URL="https://ci.ubports.com/job/focal-hybris-rootfs-arm64/job/master/lastSuccessfulBuild/artifact/ubuntu-touch-android9plus-rootfs-arm64.tar.gz" ./build/prepare-fake-ota.sh out/device_${DEVICE}_usrmerge.tar.xz ota
    - mkdir -p out
    - ./build/system-image-from-ota.sh ota/ubuntu_command out
    - mv out/rootfs.img out/ubuntu.img
    - git clone -b sweet-11.0 https://github.com/KernelPanic-OpenSource/UBPorts.git
    - cp -r out/ubuntu.img UBPorts/data/
    - cp -r out/boot.img UBPorts/data/
    - cd UBPorts/
    - wget -O data/firmware-sweet.zip https://github.com/KernelPanic-OpenSource/UBPorts/releases/download/Miui-V12.5.9.0-Sweet/fw_sweet_miui_SWEETGlobal_V12.5.9.0.RKFMIXM_9a9a09a8de_11.0.zip
    - wget -O data/firmware-sweetin.zip https://github.com/KernelPanic-OpenSource/UBPorts/releases/download/Miui-V12.5.9.0-Sweet/fw_sweetin_miui_SWEETININGlobal_V12.5.10.0.RKFINXM_dd18557436_11.0.zip
    - zip -rv9 "UBPorts-Focal-Sweet-halium-11.0-$(date +"%d-%m-%Y")-Devel.zip" *
    - rclone copy -v UBPorts-Focal-Sweet-halium* cirrus:Dev/UBPorts/"$(date +'%d-%m-%Y')"/
    - cd ..
  artifacts:
    paths:
      - out/boot.img
      - out/ubuntu.img
  when: manual
